name: Deployment
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]
    steps:
      - name: Clone Project
        uses: actions/checkout@v5
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install Dependencies
        run: pnpm install
      - name: test the project
        run: pnpm run test
        id: test
      - name: Upload test results
        if: ${{ steps.test.outcome == 'failure' }} && ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: test report
          path: test.json
  report:
    needs: test
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    steps:
      - name: Download test report
        uses: actions/download-artifact@v5
        with:
          name: test report
      - name: Display test report
        run: cat test.json
